version: "3.7"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  nginx:
    image: nginx:alpine
    container_name: nz01
    ports:
      - "8000:8000"
    volumes:
      - ./CVE:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - djangonetwork
  web:
    build:
      context: .
      dockerfile: compose/django/Dockerfile
    container_name: dz01
    restart: always
    depends_on:
      - db
    volumes:
      - ./CVE:/src
    expose:
      - "8001"
    env_file:
      - ./.envs/.django
    networks:
      - djangonetwork
  db:
    build:
      context: .
      dockerfile: compose/postgres/Dockerfile
    container_name: pz01
    ports:
      - "5432:5432"
    env_file:
      - ./.envs/.postgres
    #volumes:
      #- local_postgres_data:/var/lib/postgresql/data
      #- local_postgres_data_backups:/backups
    networks:
      - djangonetwork

networks:
  djangonetwork:
    #driver: bridge
